language: node_js
node_js:
  - latest
dist: bionic
addons:
  apt:
    sources:
      - ['llvm-toolchain-bionic-4.0']
    packages:
      - clang-format-9
before_install:
  - npm ci
script:
  - remark ./docs -o --silent
  - git status -s | wc -l
after_failure:
  - git add .
  - git commit --author "24OI-bot <15963390+24OI-bot@users.noreply.github.com>" -m "[ci skip] style: lint files with remark-lint"
  - git push origin
